import { test, expect } from '@playwright/test';
//import { todo } from 'node:test';

test('test to run app @sanity', async ({ page }) => {
  await page.goto('https://todomvc.com/examples/react/dist/#/completed');
  await page.locator('html').click();
  await page.getByTestId('text-input').click();
  await page.getByTestId('text-input').press('CapsLock');
  await page.getByTestId('text-input').fill('B');
  await page.getByTestId('text-input').press('CapsLock');
  await page.getByTestId('text-input').fill('Buy ');
  await page.getByTestId('text-input').click();
  await page.getByTestId('text-input').fill('Buy grocery');
  await page.getByTestId('text-input').press('Enter');
  await page.getByTestId('text-input').fill('r');
  await page.getByTestId('text-input').press('CapsLock');
  await page.getByTestId('text-input').press('CapsLock');
  await page.getByTestId('text-input').fill('rest');
  await page.getByRole('link', { name: 'All' }).click();
  await page.getByTestId('text-input').click();
  await page.getByTestId('text-input').fill('resting');
  await page.getByTestId('text-input').press('Enter');
  await page.getByTestId('text-input').fill('walking');
  await page.getByTestId('text-input').press('Enter');
  await page.getByTestId('text-input').fill('paying bills');
  await page.getByTestId('text-input').press('Enter');
  await page.getByRole('listitem').filter({ hasText: 'Buy grocery' }).getByTestId('todo-item-toggle').check();
  await page.getByRole('listitem').filter({ hasText: 'resting' }).getByTestId('todo-item-toggle').check();
  await page.getByRole('link', { name: 'Completed' }).click();
  await page.getByRole('link', { name: 'Active' }).click();
  await page.getByRole('link', { name: 'All' }).click();
  await page.getByRole('link', { name: 'Active' }).click();
// await expect(page.getByText('walking')).toBeVisible();
// await page.getByRole('listitem').filter({ hasText: 'paying bills' }).getByTestId('todo-item-toggle').check();
// await expect(page.getByRole('button')).toContainText('Clear completed');
  await page.goto('https://todomvc.com/examples/react/dist/#/completed');
  await page.getByRole('button', { name: 'Clear completed' }).click();
  await page.locator('html').click();
  await page.getByRole('link', { name: 'Completed' }).click();
  await page.getByRole('link', { name: 'All' }).click();
  await page.getByRole('link', { name: 'Active' }).click();
  await page.getByRole('link', { name: 'Completed' }).click();
  await page.getByTestId('footer-navigation').click();
  await page.getByRole('link', { name: 'All' }).click();
  await page.getByTestId('text-input').click();
  await expect(page.locator('todo-list li')).toHaveCount(5);
});
